version: '3'

services:
  db:
    image: "sqlite"
    volumes:
      - ./db:/var/lib/sqlite
    ports:
      - "5432:5432"
    environment:
      - SQLITE_DATABASE=mydatabase

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
