# Generated by Django 3.2.11 on 2022-10-21 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=2000, null=True)),
                ('info', models.TextField()),
                ('status', models.CharField(default='A', max_length=2)),
                ('balance', models.IntegerField(default=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clinic_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('full_name', models.CharField(max_length=512)),
                ('mobile_phone', models.CharField(max_length=512)),
                ('sex', models.CharField(max_length=1)),
                ('date_birth', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=1)),
                ('cr_on', models.DateTimeField(auto_now_add=True)),
                ('up_on', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_clinic', to='dent.clinic')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('hire_date', models.DateField()),
                ('cr_on', models.DateTimeField(auto_now_add=True)),
                ('up_on', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuff_clinic', to='dent.clinic')),
                ('cr_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stuff_crby', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuff_role', to='dent.role')),
                ('up_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stuff_upby', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuff_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stuff',
                'verbose_name_plural': 'Stuff',
            },
        ),
        migrations.CreateModel(
            name='Teeth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tooth',
                'verbose_name_plural': 'Teeth',
            },
        ),
        migrations.CreateModel(
            name='Tooth_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=500, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_on', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('complaint', models.CharField(blank=True, max_length=4000, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('total_amount', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(default=0)),
                ('cr_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='treatment_cr_by', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedure_doctor', to='dent.stuff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedure_patient', to='dent.patient')),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
            },
        ),
        migrations.CreateModel(
            name='Service_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=400, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=400, null=True)),
                ('stuff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_stuff', to='dent.stuff')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=500, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_category', to='dent.service_category')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_doctor', to='dent.stuff')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Procedure_Tooth_State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dent.procedure')),
                ('tooth_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dent.tooth_state')),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedure_service', to='dent.service'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='teeth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedure_teeth', to='dent.teeth'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dent.treatment'),
        ),
        migrations.AddField(
            model_name='patient',
            name='cr_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_crby', to='dent.stuff'),
        ),
        migrations.AddField(
            model_name='patient',
            name='up_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_upby', to='dent.stuff'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('background_color', models.CharField(blank=True, max_length=128, null=True)),
                ('border_color', models.CharField(blank=True, max_length=128, null=True)),
                ('text_color', models.CharField(default='#000000', max_length=128)),
                ('status', models.IntegerField(default=1)),
                ('display', models.CharField(blank=True, default='auto', max_length=200, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_patient', to='dent.patient')),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dent.service_category')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_stuff', to='dent.stuff')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('full_name', 'mobile_phone')},
        ),
    ]
