# Generated by Django 3.2.11 on 2022-01-14 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'Clinic', 'verbose_name_plural': 'Clinics'},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('background_color', models.CharField(blank=True, max_length=128, null=True)),
                ('border_color', models.CharField(blank=True, max_length=128, null=True)),
                ('text_color', models.CharField(default='#000000', max_length=128)),
                ('status', models.IntegerField(default=1)),
                ('display', models.CharField(blank=True, default='auto', max_length=200, null=True)),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_stuff', to='dent.stuff')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
