# Generated by Django 3.2.11 on 2022-12-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0002_auto_20221026_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
