# Generated by Django 3.2.11 on 2022-12-04 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dent', '0003_procedure_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cr_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_crby', to='dent.stuff'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='up_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_upby', to='dent.stuff'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_service', to='dent.service'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='teeth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_teeth', to='dent.teeth'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dent.treatment'),
        ),
        migrations.AlterField(
            model_name='proceduretoothstate',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dent.procedure'),
        ),
        migrations.AlterField(
            model_name='proceduretoothstate',
            name='tooth_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dent.toothstate'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category', to='dent.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_doctor', to='dent.stuff'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='cr_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stuff_crby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='up_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stuff_upby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='cr_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_cr_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_doctor', to='dent.stuff'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_patient', to='dent.patient'),
        ),
    ]
