# Generated by Django 3.2.11 on 2022-12-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0004_auto_20221204_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceduretoothstate',
            name='procedure',
        ),
        migrations.AddField(
            model_name='proceduretoothstate',
            name='teeth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dent.teeth'),
        ),
        migrations.AddField(
            model_name='proceduretoothstate',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dent.treatment'),
        ),
    ]
