# Generated by Django 3.2.11 on 2022-03-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0004_patient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('full_name', 'mobile_phone')},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
    ]
