# Generated by Django 3.2.11 on 2022-12-11 11:09

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0005_auto_20221204_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='reference_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default=1, min_length=7, prefix='treat_'),
            preserve_default=False,
        ),
    ]
