# Generated by Django 3.2.11 on 2022-03-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0005_auto_20220327_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
    ]
