# Generated by Django 3.2.11 on 2022-12-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0006_treatment_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
