# Generated by Django 3.2.11 on 2022-04-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0007_patient_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_patient', to='dent.patient'),
            preserve_default=False,
        ),
    ]
