# Generated by Django 3.2.11 on 2022-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0007_alter_treatment_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='reference_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
