# Generated by Django 3.2.11 on 2022-04-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0009_procedure_service_teeth_treatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_doctor', to='dent.stuff'),
            preserve_default=False,
        ),
    ]
